-- ============================================================================
--  DBA Incident War-Room — reference schema
--  A captured incident snapshot + a past-incident knowledge base (vectors).
--  seed.py creates these and fills the embeddings; this file is for reference.
--  Table names are prefixed so they don't clash with the credit-debate demo.
-- ============================================================================

-- The incident under debate ---------------------------------------------------
CREATE TABLE incidents (
  incident_id   NUMBER PRIMARY KEY,
  title         VARCHAR2(200),
  severity      VARCHAR2(20),          -- SEV1 | SEV2 | SEV3
  opened_at     TIMESTAMP DEFAULT SYSTIMESTAMP,
  symptom_text  VARCHAR2(4000)
);

-- Captured metrics at incident time ------------------------------------------
CREATE TABLE incident_metrics (
  incident_id   NUMBER,
  metric_name   VARCHAR2(60),
  metric_value  VARCHAR2(200),
  normal_range  VARCHAR2(60),
  note          VARCHAR2(400)
);

-- Captured v$session-like snapshot (the blocking chain) -----------------------
CREATE TABLE session_snapshot (
  incident_id       NUMBER,
  sid               NUMBER,
  serial#           NUMBER,
  username          VARCHAR2(40),
  status            VARCHAR2(12),       -- ACTIVE | INACTIVE
  sql_id            VARCHAR2(20),
  event             VARCHAR2(120),
  blocking_session  NUMBER,             -- NULL if not blocked
  secs_in_wait      NUMBER,
  module            VARCHAR2(60)
);

-- Captured v$sql-like snapshot ------------------------------------------------
CREATE TABLE sql_snapshot (
  incident_id          NUMBER,
  sql_id               VARCHAR2(20),
  sql_text             VARCHAR2(1000),
  executions           NUMBER,
  elapsed_sec_per_exec NUMBER,
  plan_hash            NUMBER,
  note                 VARCHAR2(400)
);

-- Past-incident knowledge base with a VECTOR embedding ------------------------
-- EMBED_DIM must match your embedding model (text-embedding-3-small = 1536).
CREATE TABLE past_incidents (
  past_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title            VARCHAR2(200),
  category         VARCHAR2(40),
  symptom_text     VARCHAR2(4000),
  resolution_text  VARCHAR2(4000),
  embedding        VECTOR(1536, FLOAT32)
);

CREATE VECTOR INDEX past_incidents_hnsw_idx
  ON past_incidents (embedding)
  ORGANIZATION INMEMORY NEIGHBOR GRAPH
  DISTANCE COSINE
  WITH TARGET ACCURACY 95;

-- The similarity query incident_search generates ------------------------------
--   SELECT title, category,
--          ROUND(VECTOR_DISTANCE(embedding, TO_VECTOR(:v), COSINE), 4) AS distance,
--          symptom_text, resolution_text
--   FROM   past_incidents
--   ORDER  BY VECTOR_DISTANCE(embedding, TO_VECTOR(:v), COSINE)
--   FETCH  APPROX FIRST 4 ROWS ONLY;
